### ISSUE TITLE
ドキュメントの一部に誤りがあります。

### ISSUE THREAD

**Issue by KanaSakaguchi** [ethnamphp/ethnamdoc#1]
Ethnamのチュートリアルを終えてドキュメントの一部修正したいと思ったのですが、
htmlで書かれているこちらのリポジトリにプルリクを送ればよいでしょうか？
Markdown書かれているhttps://github.com/ethnamphp/ethnam/tree/master/docの方にもプルリクを送った方がよいでしょうか？
よろしくお願いいたします。
@DQNEO 

<hr>

一応以下に修正したい箇所を書きます。
- [インストール](http://ethnamphp.github.io/ethnamdoc/10-install.html)に描かれているcomposer.jsonのethnamパッケージの指定<br>
  →dquneo/ethnamのままになっているのでethnam/ethnamに修正
- 接続URLのポート番号が[インストール](http://ethnamphp.github.io/ethnamdoc/10-install.html)に書かれているもの(8080)とそれ以外(8000)とで違う<br>
  →[インストール](http://ethnamphp.github.io/ethnamdoc/10-install.html)に書かれている定番の8080に統一<br>
  　もしくは他に合わせて8000で統一<br>
  (私がURLをコピペしてアクセスした時にHelloアクションに接続できずにいくらか悩んでしまったので。)
- [実用的なアプリケーション開発 5 ビジネスロジック(実装)](http://ethnamphp.github.io/ethnamdoc/17-business-logic-actual.html)に書かれているインクルード部分は、実際のファイルではrequire_onceになっている<br>
  →ファイルに合わせてrequire_onceに修正

**Comment by DQNEO** [comment]
@KanaSakaguchi Markdownの方にPRしてください。HTML版はビルド生成物なので。
- パッケージ名の修正→ OKです
- ポート番号 → どっちでもいいですが、8000の方がすっきりして覚えやすいのでこれにしましょう
- require_once → OKです。

よろしくお願いしますmm

**Comment by KanaSakaguchi** [comment]
承知いたしました。
ではそのようにいたします。
@DQNEO

**Comment by DQNEO** [comment]
反映しました。

**Comment by KanaSakaguchi** [comment]
ありがとうございました。
